### ISSUE TITLE
Pod `SwiftSoup` hang archiving build

### ISSUE THREAD

**Issue by woodenlabs** [scinfu/SwiftSoup#129]
I am using Xcode 11 and SwiftSoup make app hang when archiving build and i have tried [https://stackoverflow.com/questions/58001433/xcode-11-stuck-on-archiving](url) to solve issue and it is working so please provide solution for same.

**Comment by 224XS** [comment]
I don't understand you question.
Yes, there is a bug in the Xcode 11 Swift compiler than leads to an infinite loop when archiving the SwiftSoup pod. This is well documented in issue 14 here.  Apparently you read it because you say "it is working".  Be aware that turning off optimization does not work for everyone.  If you know the answer to the compiler hang, what do you mean "provide solution for same."
